### ISSUE TITLE
-fopenmp option unsupported?

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/xGadgetron#1]
On a Mac during installation I get:

553:~/iUtilities$ make
/usr/bin/g++ -O3 -fopenmp -fPIC -std=c++11 -DNDEBUG -c -o ci_tw.o ci_tw.cpp
clang: error: unsupported option '-fopenmp'
make: *** [ci_tw.o] Error 1

554:~/iUtilities$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
555:~/iUtilities$

**Comment by evgueni-ovtchinnikov** [comment]
Just remove –fopenmp, it is not needed (no idea how it ended up there).
