### ISSUE TITLE
forked gadgetron

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/xGadgetron#8]
Hi,

I am trying to run demo6.m using MATLAB with an instance of Gadgetron that is more recent than the forked version on the CCP GitHub. There seems to have been an updating of some gadget names e.g. GenericCartesianGrappaReconGadget used by demo6 is now called GenericRecon... in later versions of Gadgetron.

Any chance that the CCP version of Gadgetron will be updated soon (along with the other necessary changes)? It is now 315 commits behind. 

David

**Comment by KrisThielemans** [comment]
currently you still need the upstream_update branch to work with recent Gadgetron. we will merge soon.
